export const FETCH_COMMENTS_REQUEST="FETCH_COMMENTS_REQUEST";
export const FETCH_COMMENTS_FAILURE="FETCH_COMMENTS_FAILURE";
export const FETCH_COMMENTS_SUCCESS="FETCH_COMMENTS_SUCCESS";
export const ADD_ONE_COMMENT="ADD_ONE_COMMENT";
export const DELETE_ONE_COMMENT="DELETE_ONE_COMMENT";