export const FETCH_ONE_COMMENT_REQUEST="FETCH_ONE_COMMENT_REQUEST";
export const FETCH_ONE_COMMENT_FAILURE="FETCH_ONE_COMMENT_FAILURE";
export const FETCH_ONE_COMMENT_SUCCESS="FETCH_ONE_COMMENT_SUCCESS";
export const NO_COMMENT_SELECTED="FETCH_ONE_COMMENT_SUCCESS";
export const DELETE_COMMENT_ID="DELETE_COMMENT_ID";